import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/navbar/navbar.component";
import SideNav from "@/components/sidenav/sidenav.component";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ minHeight: "100vh" }}>
        <Providers>
          <Navbar />
          <Box display={"flex"}>
            <Box>
              <SideNav />
            </Box>
            <Box flex={1}>{children}</Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
